// Module included in the following assemblies:
//
// * installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.adoc
// * installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc

ifeval::["{context}" == "installing-vsphere-installer-provisioned-customizations"]
:customization:
endif::[]
ifeval::["{context}" == "installing-restricted-networks-installer-provisioned-vsphere"]
:restricted:
endif::[]

:_mod-docs-content-type: CONCEPT
[id="installation-installer-provisioned-vsphere-config-yaml_{context}"]
= Sample install-config.yaml file for an installer-provisioned VMware vSphere cluster

You can customize the `install-config.yaml` file to specify more details about your {product-title} cluster's platform or change the values of the required parameters.

ifdef::restricted[]
[NOTE]
====
The sample `install-config.yaml` file shows the `clusterOSImage` parameter to specify the URL for the {op-system-first} image. As an alternative to this configuration, you can use the `topology.template` parameter to point to the path in your vCenter environment that includes an {op-system} image in Open Virtual Appliance (OVA) format.
====
endif::restricted[]

[source,yaml]
----
apiVersion: v1
baseDomain: example.com
pullSecret: '{"auths": ...}'
sshKey: ssh-ed25519 AAAA...
compute:
- name:  <worker_node>
  platform: {}
  replicas: 3
controlPlane:
  name: <parent_node>
  platform: {}
  replicas: 3
metadata:
  name: test
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
platform:
  vsphere:
    apiVIPs:
    - 10.0.0.1
    failureDomains:
    - name: <failure_domain_name>
      region: <default_region_name>
      server: <fully_qualified_domain_name>
      topology:
        computeCluster: "/<data_center>/host/<cluster>"
        datacenter: <data_center>
        datastore: "/<data_center>/datastore/<datastore>"
        networks:
        - <VM_Network_name>
      zone: <default_zone_name>
    ingressVIPs:
    - 10.0.0.2
    vcenters:
    - datacenters:
      - <data_center>
      password: <password>
      port: 443
      server: <fully_qualified_domain_name>
      user: administrator@vsphere.local
----
 The base domain of the cluster. All DNS records must be sub-domains of this base and include the cluster name.
 The `controlPlane` section is a single mapping, but the `compute` section is a sequence of mappings. To meet the requirements of the different data structures, the first line of the `compute` section must begin with a hyphen, `-`, and the first line of the `controlPlane` section must not. Only one control plane pool is used.
 The cluster name that you specified in your DNS records.
 Optional: Provides additional configuration for the machine pool parameters for the compute and control plane machines.
+
[IMPORTANT]
====
The VIPs, `apiVIP` and `ingressVIP`, must come from the same `networking.machineNetwork` segment. For `apiVIP` and for `ingressVIP`, if the `networking.machineNetwork` is `10.0.0.0/16` then API VIPs and Ingress VIPs must be in one of the `10.0.0.0/16` machine networks.
====
 Establishes the relationships between a region and zone. You define a failure domain by using vCenter objects, such as a `datastore` object. A failure domain defines the vCenter location for {product-title} cluster nodes.
 The path to the vSphere datastore that holds virtual machine files, templates, and ISO images.
+
[IMPORTANT]
====
You can specify the path of any datastore that exists in a datastore cluster. By default, Storage vMotion is automatically enabled for a datastore cluster. Red Hat does not support Storage vMotion, so you must disable Storage vMotion to avoid data loss issues for your {product-title} cluster.

If you must specify VMs across multiple datastores, use a `datastore` object to specify a failure domain in your cluster's `install-config.yaml` configuration file. For more information, see "VMware vSphere region and zone enablement".
====
 Optional: Provides an existing resource pool for machine creation. If you do not specify a value, the installation program uses the root resource pool of the vSphere cluster.
 Optional: Each VM created by {product-title} is assigned a unique tag that is specific to the cluster. The assigned tag enables the installation program to identify and remove the associated VMs when a cluster is decommissioned. You can list up to ten additional tag IDs to be attached to the VMs provisioned by the installation program.
 The ID of the tag to be associated by the installation program. For example, `urn:vmomi:InventoryServiceTag:208e713c-cae3-4b7f-918e-4051ca7d1f97:GLOBAL`. For more information about determining the tag ID, see the link:https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vcenterhost.doc/GUID-E8E854DD-AA97-4E0C-8419-CE84F93C4058.html[vSphere Tags and Attributes documentation].
 The vSphere disk provisioning method.
ifdef::customization[]
 The cluster network plugin to install. The default value `OVNKubernetes` is the only supported value.
endif::customization[]
ifdef::restricted[]
 The location of the {op-system-first} image that is accessible from the bastion server.
 For `<local_registry>`, specify the registry domain name, and optionally the
port, that your mirror registry uses to serve content. For example
`registry.example.com` or `registry.example.com:5000`. For `<credentials>`,
specify the base64-encoded user name and password for your mirror registry.
 Provide the contents of the certificate file that you used for your mirror registry.
 Provide the `imageContentSources` section from the output of the command to mirror the repository.
endif::restricted[]

[NOTE]
====
In {product-title} 4.12 and later, the `apiVIP` and `ingressVIP` configuration settings are deprecated. Instead, use a list format to enter values in the `apiVIPs` and `ingressVIPs` configuration settings.
====

ifeval::["{context}" == "installing-vsphere-installer-provisioned-customizations"]
:!customization:
endif::[]
ifeval::["{context}" == "installing-restricted-networks-installer-provisioned-vsphere"]
:!restricted:
endif::[]
